Stroymagazin/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (all_posts,posts_by_category,post_detail,post_created,post_ubdare,post_delete,category_created, category_ubdate,category_delete,
                    user_login,user_logout,user_register,profile,create_comment)

urlpatterns = [
    path('',all_posts,name='index'),
    path('category/<int:category_id>/',posts_by_category,name='bolim'),
    path('detail/<int:pk>/',post_detail,name='post_detail'),
    path('add/',post_created,name='post_created'),
    path('update/<int:pk>/',post_ubdare,name='post_update'),
    path('delete/<int:pk>/',post_delete,name='post_delete'),
    path('add_category/',category_created,name='category_created'),
    path('category_update/<int:pk>/',category_ubdate,name='category_ubdate'),
    path('delete_category/<int:pk>/',category_delete,name='category_delete'),
    path('login/',user_login,name='login'),
    path('logout/',user_logout,name='logout'),
    path('register/',user_register,name='register'),
    path('profile/<str:username>/',profile,name='profile'),
    path('add_comment/<int:post_id>/',create_comment,name="create_comment"),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255,verbose_name='Kategoriya',unique=True)


    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoryalar'
        ordering = ['title']
class Post(models.Model):
    name = models.CharField(max_length=255,verbose_name='Mahsulot nomi')
    price = models.CharField(max_length=100,verbose_name='Narhi')
    content = models.TextField(blank=True,null=True,verbose_name='Mahsulot haqida')
    photo = models.ImageField(verbose_name="Rasmi",upload_to='photos/',null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True,verbose_name='Kiritilgan vaqti')
    update = models.DateTimeField(auto_now=True,verbose_name='Tahrirlangan vaqti')
    views = models.IntegerField(default=0,verbose_name='korishlar soni')
    published = models.BooleanField(default=True,verbose_name='Saytga chiqarish')
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='kategoriya')
    author = models.ForeignKey(User,on_delete=models.CASCADE)



    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Mahsulot'
        verbose_name_plural = 'Mahsulotlar'
        ordering = ('-pk',)

class UserProfile(models.Model):
    userphoto = models.ImageField(upload_to='users/',null=True,blank=True)
    status = models.CharField(max_length=150,null=True,blank=True)
    adress = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=13,null=True,blank=True)
    mobile = models.CharField(max_length=13,null=True,blank=True)
    sayt = models.URLField(null=True,blank=True)
    github = models.CharField(max_length=255,null=True,blank=True)
    telegram = models.CharField(max_length=255,null=True,blank=True)
    instagram = models.CharField(max_length=255,null=True,blank=True)
    fasebook = models.CharField(max_length=255,null=True,blank=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.user.username}"

class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.text

templates/components/_navbar.html
{% load static %}


<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <!-- Container wrapper -->
    <div class="container">
        <!-- Navbar brand -->
        <a class="navbar-brand me-2" href="{% url 'index' %}">
            <img
                    src="{% static 'blog/img/img.png' %}"
                    height="32"
                    alt="MDB Logo"
                    loading="lazy"
                    style="margin-top: -1px;"
            />
        </a>

        <!-- Toggle button -->
        <button
                data-mdb-collapse-init
                class="navbar-toggler"
                type="button"
                data-mdb-target="#navbarButtonsExample"
                aria-controls="navbarButtonsExample"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                {% if perms.blog.add_post %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_created' %}">Mahsulot qo'shish</a>
                </li>
                {% endif %}
            </ul>
            <!-- Left links -->

            <div class="d-flex align-items-center">
                {% if request.user.is_authenticated %}
                <!-- Avatar -->
                <div class="dropdown">
                    <a
                            data-mdb-dropdown-init
                            class="dropdown-toggle d-flex align-items-center hidden-arrow"
                            href="#"
                            id="navbarDropdownMenuAvatar"
                            role="button"
                            aria-expanded="false"
                    >
                        <img
                                src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                                class="rounded-circle"
                                height="25"
                                alt="Black and White Portrait of a Man"
                                loading="lazy"
                        />
                    </a>
                    <ul
                            class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuAvatar"
                    >
                        <li>
                            <a class="dropdown-item" href="{% url 'profile' request.user.username %}">My profile</a>
                        </li>


                        <li>
                            <a class="dropdown-item" href=" {% url 'logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
                {% else %}
                <a href="{% url 'login' %}" data-mdb-ripple-init type="button" class="btn btn-link px-3 me-2">
                    Login
                </a>
                <a href="{% url 'register' %}" data-mdb-ripple-init type="button" class="btn btn-primary me-3">
                    Sign up for free
                </a>
                {% endif %}



            </div>
        </div>
        <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->